version: '3'

services:
  sre-iti-clientes:
    image: felipebatista765/sre-iti-clientes
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:latest
    command: 
      - '--config.file=/prometheus-config/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus-banco'
    volumes:
      - "./prometheus-config:/prometheus-config"
      - ./data/prometheus/:/etc/prometheus/
#      - "./data/prometheus-banco:/prometheus-banco"
    ports:
      - 9090:9090
    depends_on:
      - sre-iti-clientes

  grafana:
    image: grafana/grafana 
    volumes:
      - "./data/grafana:/var/lib/grafana"
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  alertmanager:
      image: prom/alertmanager
      ports:
        - 9093:9093
      volumes:
        - ./data/alertmanager/:/etc/alertmanager/
      restart: always
      command:
        - '--config.file=/etc/alertmanager/config.yml'
        - '--storage.path=/alertmanager'
      depends_on:
        - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    depends_on:
      - prometheus


networks:
    development-network:
        driver: bridge
